name: Publish package to GitHub Packages
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: maven-settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "github", "username": "dummy", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false
      - name: Print settings xml
        run: cat /home/runner/.m2/settings.xml
      - name: Publish package
        #run: mvn --batch-mode deploy
        run: mvn test
        env:
          GITHUB_TOKEN_REF: ${{ secrets.GH_PAT_FOR_ACTIONS_TOKEN }}
